"""
Find the extra character

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s 
and then adding one more letter at a random position.
Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e
"""

def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    ch = 0
    for char in s + t:  # or looping separately
        ch ^= ord(char)  # ord() returns int representing Unicode char
    return chr(ch)
    # Time: O(N), Space: O(1)

